version: '2.4'

services:
  api:
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:12.3
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=testpass
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db-data:
