version: '2.4'

services:
  api:
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGHOST=postgres
      - PGPASSWORD=postgres
      - PGUSER=postgres
      - PGDATABASE=test
      - PGPORT=5432
    volumes:
      - .:/app

  db:
    image: postgres:12.3
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgres://postgres:postgres@db/test
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8090:8090

volumes:
  db-data:
